// generated by scripts/generate-level-constant-strings.js

// Entities:
pub const E__PLAYER_START: &str = "Player_start";

// Layers:
pub const L__ENTITIES: &str = "Entities";
pub const L__LEVEL_GEOMETRY: &str = "Level_Geometry";
pub const L__LEVEL_GEOMETRY_TILES: &str = "Level_Geometry_Tiles";
